export const RELATIONSHIP_TYPES = [
    "Friend",
    "Enemy",
    "Lover",
    "Family",
    "Sibling",
    "Parent",
    "Child",
    "Spouse",
    "Mentor",
    "Student",
    "Rival",
    "Ally",
    "Colleague",
    "Servant",
    "Master",
    "Other",
];

export const RELATIONSHIP_COLORS: Record<string, string> = {
    Friend: "bg-green-500",
    Enemy: "bg-red-500",
    Lover: "bg-pink-500",
    Family: "bg-blue-500",
    Sibling: "bg-blue-400",
    Parent: "bg-blue-600",
    Child: "bg-blue-300",
    Spouse: "bg-pink-600",
    Mentor: "bg-purple-500",
    Student: "bg-yellow-500",
    Rival: "bg-orange-500",
    Ally: "bg-teal-500",
    Colleague: "bg-slate-500",
    Servant: "bg-stone-500",
    Master: "bg-indigo-500",
    Other: "bg-gray-500",
};
